// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Volumes/BackupMaycon/github-repositories/expo-uniasselvi-academic/node_modules/react');
var { Component } = React;
var ReactNative = require('/Volumes/BackupMaycon/github-repositories/expo-uniasselvi-academic/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('expo-uniasselvi-academic', appParameters);
});
require('/Volumes/BackupMaycon/github-repositories/expo-uniasselvi-academic/index.js');